[package]
name = "qpipe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.13"
futures-util = "0.3"
log = "0.4"
quinn = "0.8"
rcgen = "0.9"
rustls = "0.20"
tokio = { version = "1", features = ["rt", "time", "macros", "io-util"] }

[dev-dependencies]
tempfile = "3"
